# AUTOGENERATED FILE -- Don't change this file unless you know what you are doing! 

RACK_ENV = ENV["RACK_ENV"] ||= "development" unless defined? RACK_ENV
require File.join(File.dirname(__FILE__), '/config/boot.rb')
run Padrino.application