# AUTOGENERATED FILE -- Don't change this file unless you know what you are doing! 
PADRINO_ROOT = File.dirname(__FILE__) + '/..' unless defined? PADRINO_ROOT

# At the moment we load it from lib
Dir[PADRINO_ROOT + "/vendor/padrino/**/lib"].each do |gem|
  $:.unshift gem
end

require 'padrino'
Padrino.load!
