require "rake/clean"
require "rake/gempackagetask"
require 'fileutils'
include FileUtils

gems = [
  "padrino-core",
  # "padrino-cache",
  "padrino-gen",
  "padrino-helpers",
  "padrino-mailer",
  "padrino-routing",
  "padrino"
]

%w(clean install uninstall gemspec package release).each do |task_name|
  desc "Run #{task_name} for all projects"
  task task_name do
    gems.each do |dir|
      Dir.chdir(dir) { sh "#{Gem.ruby} -S rake #{task_name}" }
    end
  end
end